disabled_rules:
  - line_length
  - type_name
  - function_body_length
  - identifier_name
  - trailing_whitespace
  - todo

opt_in_rules: # some rules are only opt-in
  - force_unwrapping
  - empty_count
  - conditional_binding_cascade

included:
  - SnackView/Classes

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Example
  - Carthage
  - Pods

vertical_whitespace:
  max_empty_lines: 2

function_body_length:
  - 125 #warning
  - 200 #error

cyclomatic_complexity:
  warning: 2 # two nested ifs are acceptable
  error: 4   # 4 nested ifs shows warning, 5 causes compile error

identifier_name:
  min_length: # only min_length
    error: 4 # only error

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  - 1000 #warning

reporter: "json"
